image:
  repository: <YOUR_ACR_NAME>.azurecr.io/nextjsbasicapp
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: nextjs.example.internal  # Replace with your internal DNS name
      paths:
        - path: /
          pathType: Prefix
  tls: [] # Can be enabled later with cert-manager
