image:
  repository: nextjs-acr.azurecr.io/nextjsbasicapp
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: nextjs.aks.private.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextjsapp-tls
      hosts:
        - nextjs.aks.private.local
