name: Secure AKS Deployment

on:
  push:
    branches: [ main ]

env:
  ACR_NAME: youracrname
  CLUSTER_NAME: myAKSCluster
  RG: aks-rg
  APP_NAME: nextjsbasicapp

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      run: az acr login --name $ACR_NAME

    - name: Scan Dockerfile for security (DevSecOps)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $ACR_NAME.azurecr.io/$APP_NAME:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t $ACR_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG ./app
        docker push $ACR_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group $RG --name $CLUSTER_NAME --admin

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy App with Helm
      run: |
        helm upgrade --install nextjsapp ./helm/nextjsapp \
          --namespace default \
          --set image.repository=$ACR_NAME.azurecr.io/$APP_NAME \
          --set image.tag=$IMAGE_TAG
